### ISSUE TITLE
Font Not Updating

### ISSUE THREAD

**Issue by pbesceur** [LukeSmithxyz/dwm#102]
even after compiling the config.h, some of the UI still shows the default font. is there a way to change it?
![pic-full-200809-0055-57](https://user-images.githubusercontent.com/69401718/89718814-950ddb80-d9db-11ea-99a2-85bd96c555dd.png)

**Comment by LukeSmithxyz** [comment]
dwm has nothing to do with it whatsoever. Edit `~/.config/fontconfig/fonts.conf`.
