### ISSUE TITLE
autostart patch

### ISSUE THREAD

**Issue by hakova** [LukeSmithxyz/dwm#104]
Hi all,

I am trying to apply the autostart patch to dwm ([here](https://dwm.suckless.org/patches/autostart/dwm-autostart-20200610-cb3f58a.diff)) without success. As far as I understand, this is probably due to heavy modification of the dwm.1 and dwm.c files in the source code by this branch. Is there a simple enough way to tackle this problem?

The reason I would like to install this patch is autostarting protonmail-bridge, which is necessary to access this email account. 

Thanks!

**Comment by drake-newell** [comment]
Just put it in .xprofile

**Comment by hakova** [comment]
Duh! Thank you very  much @drake-newell !
