### ISSUE TITLE
st cannot display CJK chars or emojis if invoked by dwm

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/dwm#125]
Hi Luke,

So what happened is, when I open a st instance using
**$ ~/.config/st/st
$ /usr/local/bin/st**
or simply
**$ st (which i believe points to the binary in /usr/local/bin)**
they all work just fine: I can copy & paste CJK characters/emojis into the terminal:
![pic-selected-201031-1218-57](https://user-images.githubusercontent.com/35414794/97784278-cbd73600-1b73-11eb-9864-7196f5708479.png)
![pic-selected-201031-1220-36](https://user-images.githubusercontent.com/35414794/97784283-d1348080-1b73-11eb-88e8-69492b1daf62.png)
and if I open a newsboat instance from there, the rss feeds with CJK characters are perfectly displayed.

Now, if I open a st from dwm keybindings, it looks like this:
![pic-selected-201031-1219-06](https://user-images.githubusercontent.com/35414794/97784294-e4dfe700-1b73-11eb-9b95-8eff1d31ac22.png)
![pic-selected-201031-1220-55](https://user-images.githubusercontent.com/35414794/97784297-e7424100-1b73-11eb-8992-d186b59eb682.png)

I was wondering if you have any idea why this could happen? Thanks in advance!

Best regards,
Greg

**Comment by nho1ix** [comment]
I've had that happen when I was editing Luke's bash dwmblocks scripts via the st terminal to update the icons with FontAwesome icons. I'm not entirely sure of this but I guess it's a bug with how st renders emojis

**Comment by LukeSmithxyz** [comment]
If you're *not* using my exact build of dwm, it's possible that your build is enforcing its own font configuration for st instances spawned by dwm. The default builds of dwm do that for some reason.
