### ISSUE TITLE
dwmblocks has 2 volume % indicator

### ISSUE THREAD

**Issue by codeitlikemiley** [LukeSmithxyz/dwm#13]
would love to remove this but ive installed the dwm from aur
fresh from larbs install...

would love if you could patch this up and push to aur...

**Comment by kronikpillow** [comment]
[solution](https://github.com/LukeSmithxyz/LARBS/issues/142#issuecomment-564643784)

I think the one without off is the correct one, as alsa doesn't have a off status, when its muted its set to 0 ... :) but not quite sure :) either way both work

I'v already patched/fixed a few minor things, and made a pull request, both on dwm and dwmblocks, but luke doesn't seem to be accepting them for a while now :)
