### ISSUE TITLE
statusbar font

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwm#133]
hey luke, i'v changed the size of the font in the config file, and for some reason its not being respected,
how do i change the size of the font in the statusbar your build?

**Comment by LukeSmithxyz** [comment]
Works fine on my side. What it might be is that you have an Xresources size/font that overrides the dwm size/font. In that case, just change your Xresources font from `*.font:` to `st.font:` or for whatever specific programs you want it for exclusively or have a `dwm.font:` line that gives your true preferences for it.

**Comment by kronikpillow** [comment]
no that's not the case here luke, xresources is disabled on my side, but even when I tried setting the font via xresources it set the font across entire dwm and st except the statusbar, the status bar stays frozen at the original font size

**Comment by kronikpillow** [comment]
ok, so to verify that it's broken I have reset my home directory to git origin/master (default LARBS dotfiles) and I have reset everything in .loocal/src/ to origin/master as well to verify that everything is at its default settings including dwm, and dmwblocks, then I have gone to ~/.config/x11/Xresources and edited it to 

```
*.font: monospace:size=6
dwm.font: monospace:size=6
```
`and removed the # in ~/.config/x11/xprofile on the xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &` line on ~/.config/x11/.xprofile
and the following [screenshot](https://0x0.st/iR6z.png)  is the result, as you can see the font on the terminal is puny, while the font on the statusbar is huge in comparison 
so ... I'd say mate that it definitely doesn't work, can someone else verify this please by replicating the steps?

**Comment by LukeSmithxyz** [comment]
Okay, I know what the issue is with the Xresources. It's just something I haven't managed to update. In bc040702d9cd576a055f87dab7db92528fadfef2 I moved to a new xresources patch to also read non-color variables. I haven't made the font variable compatible yet.

As to the original issue, changing font size by manually recompiling works fine for me though. Are you sure you were renewing dwm (super+backspace)?

**Comment by kronikpillow** [comment]
yes 100% sure ... I sudo make install ... then mod+backspace renew dwm, font stays in the original size ... I think it's definitely tied to the font not being variable compatible

**Comment by kronikpillow** [comment]
hm... something's off, after i reinstalled my system last night, dwm font size changes if changed in config.h, but doesn't change if loaded with .xresources hm.... Unless you did a new commit that fixed the issue, I guess i switched the other way around in my head when I was opening this issue :D
