### ISSUE TITLE
dwm doesn't load xresources on reboot

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwm#135]
I have added the nord xresources theme to ~/.config/x11/xresources

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & is uncommented in ~/.config/x11/xprofile
I reboot

st loaded the new xresources theme 👍
dwm didnt ... not sure why
I reload dwm, still nothing ...
then I go to ~/.config/x11/xresources and edit it and I just hit the write to invoce your nvim script to load xresources automatically, it loads, i refresh dwm, ,and bam I have Luke's dwm in nord ... ok cool ... I restart, and same scenario, on first boot, nothing ... what am I missing?

btw the color selection in the config.h is personal selection?

**Comment by LukeSmithxyz** [comment]
I can't replicate this.

Is your dwm build the most recent?

You might want to get rid of the `&` at the end of the xrdb line and see
what happens.

**Comment by kronikpillow** [comment]
The & at end of line is in your dotfiles

**Comment by kronikpillow** [comment]
Yeah most recent one, ill try with removed &

**Comment by kronikpillow** [comment]
Even when i leave dwm and relogin, it doesn't reload the theme

**Comment by LukeSmithxyz** [comment]
What does your xresources file look like?

**Comment by kronikpillow** [comment]
[xresources](https://github.com/kronikpillow/voidrice/blob/master/.config/x11/xresources) 

The nord theme is at the bottom of it, you can also check my xprofile at [xprofile](https://github.com/kronikpillow/voidrice/blob/master/.config/x11/xprofile) 

My dotfiles are basically your dotfiles, identical and always up to date, with a nord based theme, and a few additions to your nvim config and zsh config and lf config... Iv been living in LARBS for 2.5 years, and i don't think ill ever make the switch to something else :-D i even currently run your build of dwm, but i plan to patch it with cfacts as i find it essential especially with centered master and centered floating master, also pertag is a todo on my fork of your dwm, both are maybe something to consider ur self :-)

**Comment by kronikpillow** [comment]
So to elaborate, after i login to the desktop, xresources is applied to st, dmenu, and basically everything that reads xresources, except dwm, then i need to xrdb config/x11/xresources again manually, and then mod+backspace renew dwm for dwm to actually load the colors... After, if i mod+backspace and leave dwm, and login again, dwm is again loaded without the colors.... This bug used to be present in the xrdb patch on your build as well, i made a issue on your github about it, and soon after you fixed it, now with the switch from xrdb to xresources patch the bug is back again

**Comment by LukeSmithxyz** [comment]
Running with your xresources, it's working fine on startup for me. Not
sure what's going on.

**Comment by kronikpillow** [comment]
me neither man :-/ it's driving me crazy, I will go now reinstall and do a clean larbs install to see if it still persists and will report back ... in the meanwhile you can do a check on your dwm repository and mine .. no difference except that I'v fixed the spranger variable to spcalc, as your using spcalc in keybindings, while the variable set to the command in your build is spranger (btw I did a merge request on that) and that I use Mod+S for scratchpad, and Mod+Shift+S for togglesticky, and Mod+Shift+Return for your samedir script
here is:
[kronikpillow/dwm vs lukesmith/dwm](https://github.com/LukeSmithxyz/dwm/compare/master...kronikpillow:master)
and here is:
[kronikpillow/voidrice vs lukesmith/voidrice](https://github.com/LukeSmithxyz/voidrice/compare/master...kronikpillow:master)

can you check the voidrice comparison link to see if something there could be causing it? althou I doubt it is, not many differences except a few small things here and there, and gpg-agent instead ssh-agent as i never figured out how to use pam-gnupg to unlock ssh-keys without using gpg-agent

**Comment by kronikpillow** [comment]
removing & from the xprofile line where it sources xresources solved the problem
