### ISSUE TITLE
Single window in tiling layout not fullscreen with gaps

### ISSUE THREAD

**Issue by shahzebs** [LukeSmithxyz/dwm#14]
I tried patching my build of dwm by including changes from Luke's gaps commit ([6effa70](https://github.com/LukeSmithxyz/dwm/commit/6effa70a11af058b16a219a400770cf9d593bee2)). 
I did the patch manually because I'm a noob. However, I'm pretty sure I made the changes correctly. 

My problem is that whenever I open my first window in tiling layout, it does not open in fullscreen, i.e. it opens as if it has slaves to the side of it (fullscreen means fullscreen but with the outer gaps). When opening a second window the first window becomes the slave and everything behaves as it should.
The above description applies when I have one master window. If I on the other hand reduce it to none, the window spans the entire screen.  

I'm guessing I have missed something and just adding the changes from Luke's commit might not be enough. Suggestions?

My build of [dwm](https://github.com/shahzebs/dotfiles/tree/master/dwm) (it's quite basic).

**Comment by kronikpillow** [comment]
just apply the dwm-vanitygaps patch from the suckless website instead of implementing the commit

**Comment by shahzebs** [comment]
Thank you! That fixed it
