### ISSUE TITLE
When I startx, despite having libxft-bgra installed I still crash when it attempts to render the emojis in the status bar.

### ISSUE THREAD

**Issue by TypicalProgrammr** [LukeSmithxyz/dwm#140]
To be honest, I don't even want emojis in my status bar. If I can't figure out how to fix the error then please tell me how I can at least remove the emojis. Thanks.
![error](https://user-images.githubusercontent.com/75520335/102545526-392f1f80-406b-11eb-8bb9-719ceff3d0c6.PNG)

**Comment by m-althaf** [comment]
If you want to remove dwmblocks
```
cd .local/src/dwmblocks/
sudo make uninstall
```
do you have the fonts mentioned in config.h?

**Comment by sam-vcs** [comment]
I had an issue similar to this where an Xresources value wasn't set (it was for dmenu though, so this is probably not it for you).
