### ISSUE TITLE
Is there any other way to refresh dwm.

### ISSUE THREAD

**Issue by shahid777-py** [LukeSmithxyz/dwm#145]
Is there any other way to refresh dwm without bringing all programs to 1st worksapce or tags , atleast when i change dwm colrs in xresources.

**Comment by LukeSmithxyz** [comment]
No. Not right now. If anyone knows of a patch that keeps windows consistent or is willing to add it, I will be happy to add it if it is streamlined enough, but it might not be non-stipulative.

**Comment by shahid777-py** [comment]
> No. Not right now. If anyone knows of a patch that keeps windows consistent or is willing to add it, I will be happy to add it if it is streamlined enough, but it might not be non-stipulative.

So,thats it ,right,do you think it's because dwm running in a loop,so each time we refresh it has to kill and the loop  start again,it's not like normal other WM's right.instead of loop we have to then use startx it's more disastrous than this.

**Comment by shahid777-py** [comment]
> No. Not right now. If anyone knows of a patch that keeps windows consistent or is willing to add it, I will be happy to add it if it is streamlined enough, but it might not be non-stipulative.

It seems there is a way to refresh the bar at least ,it was mentioned in the xrdb patch.

**Comment by drake-newell** [comment]
> No. Not right now. If anyone knows of a patch that keeps windows consistent or is willing to add it, I will be happy to add it if it is streamlined enough, but it might not be non-stipulative.

The only thing I've found to help mitigate dwm refreshes losing window positions is creating tag rules for basically all of my common programs (including starting st with a custom class for each tui program).

**Comment by shahid777-py** [comment]
> > No. Not right now. If anyone knows of a patch that keeps windows consistent or is willing to add it, I will be happy to add it if it is streamlined enough, but it might not be non-stipulative.
> 
> The only thing I've found to help mitigate dwm refreshes losing window positions is creating tag rules for basically all of my common programs (including starting st with a custom class for each tui program).

That seems will work, but some manual stuff not dynamic.

**Comment by drake-newell** [comment]
> > > No. Not right now. If anyone knows of a patch that keeps windows consistent or is willing to add it, I will be happy to add it if it is streamlined enough, but it might not be non-stipulative.
> > 
> > The only thing I've found to help mitigate dwm refreshes losing window positions is creating tag rules for basically all of my common programs (including starting st with a custom class for each tui program).
> 
> That seems will work, but some manual stuff not dynamic.

Yeah, true. To make it work you would probably want to set up each tag for a given task (web, terminals, music, etc)
