### ISSUE TITLE
Smart gaps patch doesn't work

### ISSUE THREAD

**Issue by Hurricane14** [LukeSmithxyz/dwm#146]
Gaps are shown when there is only one window. Tried to fix, found out that Makefile ignores vanitygaps.c changes as there is no dependency for config.h (same to shiftview.c). Thought that maybe it's because I reverted rm xrdb patch, cloned master branch, set smartgaps to 1, enablegaps to 0, compiled - same thing.

**Comment by LukeSmithxyz** [comment]
I can't replicate this problem. The smartgaps setting is working whether I change it in the source code or via xresources settings. You shouldn't be changing the `enablegaps` settings for this.
