### ISSUE TITLE
Pywal color scheme applied only after renewing dwm

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/dwm#148]
On log in dwm loads it's default colors but after renewing it loads the ones defined by pywal, while st, dmenu, zathura, dunst, etc. are always loaded with the pywal colors. 
If i log out and re-log in the behavior persists.

**Comment by kronikpillow** [comment]
[issue#135](https://github.com/LukeSmithxyz/dwm/issues/135) try this

**Comment by ghost** [comment]
> [issue#135](https://github.com/LukeSmithxyz/dwm/issues/135) try this

It doesn't fix it.

I gave up and defined the colours in Xresources.

**Comment by dartajan** [comment]
I patched it by including into ~/.config/zsh/.zshrc the following line

`(cat ~/.cache/wal/sequence &)`

do not forget the parentheses

**Comment by sam-vcs** [comment]
Dmenu looks at the xresources database each time it gets called, DWM will only ever do it on reload I believe.

**Comment by LukeSmithxyz** [comment]
Yeah, there used to be a bind to refresh the dwm scheme, but I removed that patch for efficiency. Note that you can run the sysact script (mod+backspace) and choose "renew dwm" to reload the scheme, although this will disturb your window order.

**Comment by skybreakerr** [comment]
You can just add this line in the end of your pywal script
` kill -HUP "$(pgrep -u "$USER" "\bdwm$")" `
 It will renew your dwm at the start so that you dont have to do it manually.
