### ISSUE TITLE
Installation failed because `dwmc` doesn't exist

### ISSUE THREAD

**Issue by MuntashirAkon** [LukeSmithxyz/dwm#15]
Installation failed at

```
cp -f dwm dwmc /usr/local/bin
cp: cannot stat 'dwmc': No such file or directory
make: *** [Makefile:41:install] Error 1
```

I manually checked the `Makefile`. There's indeed no option to build `dwmc`. But I found it in the `.gitignore` file. What's going on?

**Comment by LukeSmithxyz** [comment]
Fixed now. For whatever reason I had put the file in the gitignore.
