### ISSUE TITLE
window geometry for toggleable scratchpads not working.

### ISSUE THREAD

**Issue by nudnyzjeb** [LukeSmithxyz/dwm#151]
Changing `"-g", "120x34"` to `"-g", "120x34-40-40"` in config.h does not change a scratchpad's position, it stays centered. Just launching `st -g 80x21-40-40` with floating mode (mod+F) active works fine, a terminal window appears in bottom right corner.

**Comment by kronikpillow** [comment]
that's because the scratchpad is supposed to be centered by default, there is a separate patch on top of the original scratchpad patch that remembers last saved position of each scratchpad
