### ISSUE TITLE
error while running sudo make install 

### ISSUE THREAD

**Issue by santiFerra** [LukeSmithxyz/dwm#160]
dwm.c:45:10: fatal error: xcb/res.h: No such file or directory
 #include <xcb/res.h>
I'm using linux mint. I'm sorry for asking a stupid question.

**Comment by sam-vcs** [comment]
Do you have a package called `libxcb` or something similar installed?

**Comment by santiFerra** [comment]
i'm not in arch so I think i can't. Do you know of any alternative? thanks for replying.

**Comment by Fooftilly** [comment]
According to the [Linux Mint package list](https://community.linuxmint.com/index.php/software/search/) libxcb is available.

**Comment by joellidin** [comment]
I am on Ubuntu 20.04 and I get the same error even though `apt-file find xcb/res.h` shows `libxcb-res0-dev: /usr/include/xcb/res.h`.

**Comment by rmagillxyz** [comment]
Here's the list of libraries I had to install on debian to get things to work.
```
libx11-dev
libxinerama-dev
libxft-dev
libx11-xcb-dev
libxcb-res0-dev
```
and then build [libxft-bgra](https://github.com/uditkarode/libxft-bgra.git)

**Comment by golam71** [comment]
`sudo apt install libx11-dev libxinerama-dev libxft-dev libx11-xcb-dev libxcb-res0-dev`
