### ISSUE TITLE
How do you get a GUI program to work with the scratchpad patch

### ISSUE THREAD

**Issue by JimPix1** [LukeSmithxyz/dwm#164]
So I took a look at the patch on the suckless website and installed detach so I could use it for X programs. My problem is I don't know how to get it to work properly, I've done a lot of tinkering in the config.h and something like
``const char scratchpadname[] = "scratchpad";``

``const char *scratchpadcmd[] = { TERMINAL, "-t", scratchpadname, "-g", "120x34", "detach nemo" };``
does not work when i press the togglescratch keybind, what do i do to get it to work?

**Comment by rmagillxyz** [comment]
I was having issues with this too. I ended up using [tdrop](https://github.com/noctuid/tdrop) which just works. Install tdrop and add a script like this to your path, and then create a regular binding to that script. I'm still using scratchpads for some terminal bindings because it has a slightly different behavior and is just a hair quicker, but they work well together. Check it out.  

tdrop-brave:
```
#!/bin/bash
tdrop -h 99% -n 1 -m brave 
```
binding: 
`{ Mod1Mask, XK_b, spawn,		SHCMD("tdrop-brave") }`

**Comment by JimPix1** [comment]
Thank you **so** much for this! This is exactly what I've wanted for ages!
I would remove the scratchpad patch for my dwm build but I'm never able to do it since I based it off Luke's build which has a different dwm.c to what I'm used to...

**Comment by rmagillxyz** [comment]
@JimPix1 Awesome. Glad I could help. I use both, I have one terminal set using scratchpad and the other using tdrop and they drop in different sides of the split so it's useful to have both. For the gui programs like a browser, I only use tdrop. One really cool thing about scratchpads are you can start a gui program from the command line, and as long as you have swallowing enabled and you're not in a tmux session, whatever program you start now becomes a scratchpad for that binding, so yeah, using both together is amazing.

**Comment by JimPix1** [comment]
I never thought about pairing scratchpad with swallowing, that's cool!
For some reason though when I use my scratchpad binding it just opens what I want it to, and when I want to hide it I press the binding and it just opens another one, any idea on how to fix that?

**Comment by JimPix1** [comment]
Okay so when I open a scratchpad, and go to a different tag, and then press the binding, it comes up, like pulling up a tag but instead it's just the scratchpad, annoyingly I can't make the whole window disappear like tdrop or i3's scratchpad, instead it stays on the original tag I opened the scratchpad in, any way to make it just, disappear like tdrop?

**Comment by rmagillxyz** [comment]
> I never thought about pairing scratchpad with swallowing, that's cool!
> For some reason though when I use my scratchpad binding it just opens what I want it to, and when I want to hide it I press the binding and it just opens another one, any idea on how to fix that?

That's exactly why I use tdrop for the gui programs. I've only been able to get scratchpads to toggle with cli programs or cli to swallow. If you just scratchpad a terminal, you should be able to toggle it.

**Comment by JimPix1** [comment]
> > I never thought about pairing scratchpad with swallowing, that's cool!
> > For some reason though when I use my scratchpad binding it just opens what I want it to, and when I want to hide it I press the binding and it just opens another one, any idea on how to fix that?
> 
> That's exactly why I use tdrop for the gui programs. I've only been able to get scratchpads to toggle with cli programs or cli to swallow. If you just scratchpad a terminal, you should be able to toggle it.

Sorry that was actually happening with a terminal, I just did it wrong lol. I can toggle it now but how do I hide it into the scratchpad workspace? When I press the binding my terminal appears in the tag, and if I change the tag and press my binding the terminal gets pulled up like a tag, but it stays in the original tag, how do I assign it a scratchpad tag?

**Comment by rmagillxyz** [comment]
> Okay so when I open a scratchpad, and go to a different tag, and then press the binding, it comes up, like pulling up a tag but instead it's just the scratchpad, annoyingly I can't make the whole window disappear like tdrop or i3's scratchpad, instead it stays on the original tag I opened the scratchpad in, any way to make it just, disappear like tdrop?

Oh, are you using a different monitor? Scratchpad doesn't translate between the two monitors. If you're on the same monitor, but a different tag, it will persist, but if you switch to a different monitor it's like opening a fresh instance. I'm sure there's a way to change this, but I've never looked into it. Is that what you're talking about?

**Comment by JimPix1** [comment]
> > Okay so when I open a scratchpad, and go to a different tag, and then press the binding, it comes up, like pulling up a tag but instead it's just the scratchpad, annoyingly I can't make the whole window disappear like tdrop or i3's scratchpad, instead it stays on the original tag I opened the scratchpad in, any way to make it just, disappear like tdrop?
> 
> Oh, are you using a different monitor? Scratchpad doesn't translate between the two monitors. If you're on the same monitor, but a different tag, it will persist, but if you switch to a different monitor it's like opening a fresh instance. I'm sure there's a way to change this, but I've never looked into it. Is that what you're talking about?

No it's the one monitor! It's hard to explain, I can't make imy scratchpad "disappear" like in i3, I can just spawn it in one tag, and when I move to a new tab and press the key, the scratchpad is pulled up, but it's only temporary, if I changed to a new tag again my scratchpad is still in the original tag I spawned it in, pressing the key to hide it doesn't hide it
Do you understand? It's hard to explain haha

**Comment by rmagillxyz** [comment]
> > > I never thought about pairing scratchpad with swallowing, that's cool!
> > > For some reason though when I use my scratchpad binding it just opens what I want it to, and when I want to hide it I press the binding and it just opens another one, any idea on how to fix that?
> > 
> > 
> > That's exactly why I use tdrop for the gui programs. I've only been able to get scratchpads to toggle with cli programs or cli to swallow. If you just scratchpad a terminal, you should be able to toggle it.
> 
> Sorry that was actually happening with a terminal, I just did it wrong lol. I can toggle it now but how do I hide it into the scratchpad workspace? When I press the binding my terminal appears in the tag, and if I change the tag and press my binding the terminal gets pulled up like a tag, but it stays in the original tag, how do I assign it a scratchpad tag?

hmm, I'm not sure. When I switch workspaces and hit the binding again, it opens on which ever workspace I'm currently on as long as I'm on the same monitor. I've never used i3 so I have nothing to compare it to. Here is [my config](https://github.com/rmagillxyz/dwm/blob/master/config.h). The only other thing I can think of is that I forked this from luke awhile ago so maybe something has changed since that is causing that.

**Comment by JimPix1** [comment]
Tomorrow I'll do some messing and I'll see if I can get the hiding part to work, I'll get back to you tomorrow. 
Thanks for your help so far!

**Comment by JimPix1** [comment]
I got it all working! Everything is great now, I'm using dwm's scratchpad for terminals and tdrop for GUI programs!
Do you know a way to make tdrop programs be centred?

**Comment by rmagillxyz** [comment]
@JimPix1 Sorry for the late response. You've probably figured this out by now, but yes in the `tdrop` man page you'll see settings for offset, width and height.
