### ISSUE TITLE
Brave custom ad notifications cause issue with dropdown menus.

### ISSUE THREAD

**Issue by UtkarshVerma** [LukeSmithxyz/dwm#170]
I have opened an issue on Brave's repo regarding this issue.
https://github.com/brave/brave-browser/issues/17163

Basically, if I have Brave Rewards enabled, Brave shows me a custom ad notification. When I close it, dropdowns fail to open in Brave for me and I have to switch to other workspace and back again to initial workspace as a workaround to get dropdowns to work.

Is anyone else facing this issue?

**Comment by kronikpillow** [comment]
is there a way to get brave ad notifications to use the native notification system like before?
