### ISSUE TITLE
Mod + Insert Broken

### ISSUE THREAD

**Issue by wlmchen** [LukeSmithxyz/dwm#171]
It is supposed to do 

```
"xdotool type $(grep -v '^#' ~/.local/share/larbs/snippets | dmenu -i -l 50 | cut -d' ' -f1)"
```

However, I don't see any mention of `~/.local/share/larbs/snippets` anywhere and it simply causes a blank dmenu

**Comment by LukeSmithxyz** [comment]
Oh this is actually something I use on my own machine and I guess I committed here inadvertently.

I use the snippets file to store long urls and other things that are too long to type out or memorize continuously and this binding inserts a chosen one.

You can just create your own or ignore the bind. I have nothing I intend to replace it with right now so it's not harming anyone.
