### ISSUE TITLE
How do I get libxft-bgra on Linux Mint (ubuntu-based)?

### ISSUE THREAD

**Issue by JimPix1** [LukeSmithxyz/dwm#174]
So I was using lukes build on arch, but I switched to linux mint and libxft-bgra isnt in the repos, So now I don't have coloured glyphs/emoji in dwmblocks, browsers etc.
How do I get it?

**Comment by grigoriynikolaev** [comment]
#179 Have you tried these packages?

**Comment by JimPix1** [comment]
> #179 Have you tried these packages?

Just tried them and dwm still crashes when starting my dwmblocks because of the emojis

**Comment by JimPix1** [comment]
Switched to Arch again and this no longer matters
