### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by wangms168** [LukeSmithxyz/dwm#176]
How does your build of dwm realize the patch function of dwm-environmentvars-terminal-20210807-dd4b656.diff

**Comment by LukeSmithxyz** [comment]
What?

**Comment by ghost** [comment]
`cd YOUR_DWM_SOURCE_DIR`
`wget https://dwm.suckless.org/patches/environmentvars/dwm-environmentvars-terminal-20210807-dd4b656.diff`
`patch < dwm-environmentvars-terminal-20210807-dd4b656.diff`
`make; ROOT_CMD make install` (sudo or doas)
### OR
Change `#define TERMINAL "st"` (line four of config.h) to the command to run your terminal
For example:
`#define TERMINAL "urxvt"` (the only other terminal it might make sense to use)
