### ISSUE TITLE
Shudown keybinding not doing anything?

### ISSUE THREAD

**Issue by manikandanraji** [LukeSmithxyz/dwm#18]

**Comment by charlie39** [comment]
which binding?

**Comment by LukeSmithxyz** [comment]
Actually the shutdown binding and the restart are reliant on some shell script in my dotfiles. That's why. I suppose I should just build those into dwm though,

**Comment by LukeSmithxyz** [comment]
Fixed now. You no longer need my scripts for these bindings as they are hardcoded into dwm.
