### ISSUE TITLE
dwm starts even deleted from xinitrc

### ISSUE THREAD

**Issue by vanhoxx** [LukeSmithxyz/dwm#180]
I deleted the "exec dwm" lines from xinitrc but it keeps opening.

**Comment by katrushenkov** [comment]
So you wanna stay in tty after login?

**Comment by LukeSmithxyz** [comment]
In recent versions, the xinitrc used is in `~/.config/x11/xinitrc`. Are you deleting it from there?

**Comment by vanhoxx** [comment]
> In recent versions, the xinitrc used is in `~/.config/x11/xinitrc`. Are you deleting it from there?

Thanks, I tried to delete from ~/.xinitrc but as you say the correct one is .config/x11/xinitrc
