### ISSUE TITLE
Not every unicode emoji/glyph works in the dwmbar

### ISSUE THREAD

**Issue by JimPix1** [LukeSmithxyz/dwm#187]
For example the ⚡ emoji doesn't work in dwmbar/dwmblocks for me and I'm not sure why, I'm using JoyPixels as my font and I have ttf-joypixels installed onto my system. Am I missing a package or something?

**Comment by 0x14307** [comment]
You might have, did you install that AUR package described at the very bottom of the README?

**Comment by JimPix1** [comment]
Yeah, without libxft-bgra dwm would crash immediately. So it's not that

**Comment by JimPix1** [comment]
The ⚡ looks like this in dwmblocks 
![image](https://user-images.githubusercontent.com/79943327/158060728-a36c7b90-6028-468c-954a-5ffe7601e4e4.png)

**Comment by JimPix1** [comment]
The same goes for other icons like ☔ or ♻️
