### ISSUE TITLE
Tags Disappear When Nothing is on them

### ISSUE THREAD

**Issue by Mythbusters123** [LukeSmithxyz/dwm#189]
I know this is implemented for a “cleaner” user interface, but I am just curious on how to show all of the tags, no matter if they have a window on them or not. Thank you.

**Comment by matty086** [comment]
How to unsubscribe this ? I clicked >You’ve been unsubscribed from this thread.< but no effect/ shit

**Comment by ejv2** [comment]
Press Mod+0 and all tags will be active. Either that or reverse apply the [hide vacant tags ](https://dwm.suckless.org/patches/hide_vacant_tags/) patch
