### ISSUE TITLE
Adding xrdb argument to dwmc

### ISSUE THREAD

**Issue by bonnefoi** [LukeSmithxyz/dwm#19]
Hello,

Could you add the xrdb argument to dwmc :
```
1)
	case $1 in
	setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | quit | xrdb)
```

thank you very much for your work !

Love your youtube channel :)

**Comment by LukeSmithxyz** [comment]
Added this in 36abd77b8421a3ddd05584dd818e05bb36fa0e82, forgot to close this issue.
