### ISSUE TITLE
overuse of SHCMD(cmd) macro

### ISSUE THREAD

**Issue by ListeriaM** [LukeSmithxyz/dwm#191]
the `SHCMD()` macro is meant to spawn a shell, which will in turn parse the
command given to it and execute it.

this is useful in the case that you need to pipe the output of a program into
another (e.g: when pressing `MODKEY+F1`), or execute multiple commands (e.g:
`"<command1> ; <command2>"`), or access environment variables (e.g:
`$BROWSER`), etc.

but I see it being used in pretty much every keybinding, to name a few:
`SHCMD(TERMINAL " -e lf")` can be replaced by `{.v = (const char*[]){ TERMINAL,
"-e", "lf", NULL } }` or `SHCMD("mpc seek -10")` by `{.v = (const char*[]){
"mpc", "seek", "-10", NULL } }`. **Thus removing the unnecessary middleman**.

or if you'd rather use a macro: `#define SPAWN(...) {.v = (const char*[]){
__VA_ARGS__, NULL } }` or the more descriptive: `#define SPAWN(cmd, ...) {.v =
(const char*[]){ cmd, __VA_ARGS__, NULL } }` (this one requires at least one
argument) both of which you can then use the same way you use `SHCMD()`, but
I'm not sure which compilers aside from gcc support variadic macros, nor what
the systax would be for the ones that do. Nonetheless, such a macro is
functionally equivalent to the move verbose `{.v = ... }`.

**Comment by ListeriaM** [comment]
This might even be a problem with shell scripts like `sysact`. Because what is executed when you use `SHCMD("sysact")` is `/bin/sh -c sysact` which is different from `sysact`. I think the first one spawns a second shell when sysact is executed, but I could be wrong.

**Comment by LukeSmithxyz** [comment]
Yeah I had just done it this way out of laziness and got carried away with the pattern. I'll readjust the lines as they should be some time soon.

**Comment by N-R-K** [comment]
> I'm not sure which compilers aside from gcc support variadic macros

[Variadic macros are part of C99](https://en.cppreference.com/w/c/preprocessor/replace), so pretty much any C99 compiler should support it. And dwm requires a C99 compiler anyways since it uses various C99 features.
