### ISSUE TITLE
Question: Where are the dwm layouts kept?

### ISSUE THREAD

**Issue by JimPix1** [LukeSmithxyz/dwm#192]
Didn't want to have to make an issue for this one but I've been searching EVERYWHERE in the dwm build to try and find where the layouts like fibonacci etc. are kept but I just can't find them. Couldn't find them in dwm.c etc.

**Comment by ListeriaM** [comment]
they're in vanitygaps.c, you can find them by grepping for any layout function, which are enumerated in config.h in the layouts array

**Comment by JimPix1** [comment]
Thanks!
