### ISSUE TITLE
dragging tabs in a browser

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwm#199]
trying to drag tabs in Brave and reorder them, always places the dragged tab in a new window ... this behavior rarely happened before until recently ... it's very annoying, is there any known way to fix/bypass this?

**Comment by ghost** [comment]
I've noticed this as well on ungoogled chromium, no idea where it came from

**Comment by LukeSmithxyz** [comment]
It's just their design decision. If your mouse leaves the bar, it will just preemptively make a new window. Firefox browsers don't do this, you just have to be careful.
