### ISSUE TITLE
Icons?!

### ISSUE THREAD

**Issue by y0rune** [LukeSmithxyz/dwm#2]
I want to transform your i3block, but the dwm can't show the icons :( Do you have the same problem?

**Comment by astier** [comment]
Its because his dwm-font in the config.h is _monospace_. You need to set it to something like _UbuntuMono Nerd Font_. You can find and install the respective package _nerd-fonts-ubuntu-mono_ in the AUR. Don't forget the recompile and reinstall.

**Comment by y0rune** [comment]
Oh yeah you are right <3 Thank You... Sorry Mr. Luke for spam... I will find in the eix and I will change it ;)

**Comment by astier** [comment]
@linux923344  Although I do not now if you actually can set fancy image-like icons like he had in i3block.

**Comment by astier** [comment]
@linux923344  But you can make it look like the statusbar in the videos from iBSD with the font I mentioned. The [font-awesome-cheatsheet](https://fontawesome.com/cheatsheet) is a nice source to get such icons.

**Comment by y0rune** [comment]
@astier  Yeah yeah I installed and it works. Thanks <3
