### ISSUE TITLE
This is not an issue but why the keybinding for backlight is missing ??

### ISSUE THREAD

**Issue by charlie39** [LukeSmithxyz/dwm#20]
It is  there in the Suckless repository, i can't think of a reason why you won't add the binding for the backlight.
 Do let me know if it is intentional.
lf it is not, i would like to open a pull request.

**Comment by charlie39** [comment]
Also, the scripts from i3 doesn't really gell well. Like the span tags in the battery script is showing up all messed up.

**Comment by LukeSmithxyz** [comment]
A lot of kernels/init systems will automatically bind the backlight keys to the proper button so I never bothered binding them manually. My computers have them by default. You can submit a PR if you'd like.

Just removed the pango syntax from the battery script. Just an oversight.

**Comment by AlixShahid** [comment]
hey @charlie39 bind this to your config.h

{ 0, XF86XK_MonBrightnessUp,	spawn,		SHCMD("light -A 1 ; pkill -RTMIN+10 dwmblocks") },
{ 0, XF86XK_MonBrightnessDown,	spawn,		SHCMD("light -U 1 ; pkill -RTMIN+10 dwmblocks") },

in case you need a script for status bar, 


#!/bin/sh
#unicode icons 🔆 🔅 🌣

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
cur_bright=$(cat /sys/class/backlight/intel_backlight/brightness)
max_bright=$(cat /sys/class/backlight/intel_backlight/max_brightness)

#convert into percentages
perc_bright="$(($cur_bright * 100 / $max_bright))"

if [ "$cur_bright" -lt 10 ]; then
  perc_bright=1;
fi

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e light & ;;
	3) light -A 1 >/dev/null 2>/dev/null ;;
	4) light -U 1 >/dev/null 2>/dev/null ;;
	2) pgrep -x dunst >/dev/null && notify-send " Shows brightness 🔆.";;
esac

icon="🔆"
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
printf " %s%s%% \\n" "$icon""$perc_bright"

**Comment by charlie39** [comment]
sorry for the late response. I have already put the bindings in my system cuz it was not working. I see its already fixed. Okay dokey then
