### ISSUE TITLE
Patch "single_tagset" should be added

### ISSUE THREAD

**Issue by Mythbusters123** [LukeSmithxyz/dwm#207]
For people with multiple monitors. having to deal with 20, 30, or 50 tags at once is overwhelming and frankly impractical. We could have the patch https://dwm.suckless.org/patches/single_tagset/ to help with this, and have the list of tags be consistent across all monitors. This would greatly improve multi-monitor setups and the productivity with those setups.

**Comment by LukeSmithxyz** [comment]
Yeah I've thought about this. I rarely use multiple monitors, but I do feel like it's a little more intuitive for new users. It's just an issue of whether moving away from the default functionality would harm certain usecases.

**Comment by Mythbusters123** [comment]
I am currently making a patch for it so if you could merge it or create another branch and wait for people to adopt it more. Thank you 😃

**Comment by kronikpillow** [comment]
em, the approach to multi monitors is exactly why i use dwm ... i would disagree with single tagset patch ...
