### ISSUE TITLE
super + f1 doesnt display larbs documentation correctly

### ISSUE THREAD

**Issue by wjcblair** [LukeSmithxyz/dwm#208]
I have installed zathura but when I press the documentation keybind, a black panel appears with "[No name]" on it - I have no idea how to get the doc pdf to appear correctly.

**Comment by LukeSmithxyz** [comment]
Did you run the script to install or did you install all this manual?

Is groff installed?

**Comment by senchpimy** [comment]
You have zathura-pdf-mupdf installed?

**Comment by wjcblair** [comment]
I just the dwm repo - but ive since reinstalled and used LARBS as a whole so I wont be able to know what caused it. Most likely something on my behalf
