### ISSUE TITLE
question about statusbar

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwm#21]
how did you get the statusbar icons to display the Joypixels icons? I copied your font settings from your dwm build to my own, but I still get the black and white icons ... is there some patch / tweak that I'm not aware of? :)

**Comment by LukeSmithxyz** [comment]
Might have to do with your fontconfig settings if you have it automatically append some other emoji font to your monospace font before joypixels is called.

Check my fontconfig out: https://github.com/LukeSmithxyz/voidrice/blob/master/.config/fontconfig/fonts.conf

**Comment by LukeSmithxyz** [comment]
Also, in case you haven't you need to remove some code from `drw.c` as well. See my commit here: 1ded83fb3d14909b1fa7a015f48b86c947cf9658.

**Comment by kronikpillow** [comment]
I'm using larbs, but I use my own build, as for some reason I cant patch your with the deck layout it fails  (which I use a lot and find very useful) every time since the recent restart of your build plus I use the latest vanitygaps build from vanitygaps author bakkeby's repo which includes lots of layouts by default, and all are compatible with vanitygaps, eg monocle respects gaps, centered master respects gaps, spiral respects gaps, etc etc etc .... it can be found in [bakkeby/vanitygaps](https://github.com/bakkeby/dwm-vanitygaps) in the patches folder ... then I discovered his flexipatch build, which is a dream come true to ppl who don't know C :) but couldn't get the fontto display in colored icons, it's possibly that drw.c edit, I'll try it out :) thanks for letting me know

**Comment by kronikpillow** [comment]
that was it thanks :)

**Comment by LukeSmithxyz** [comment]
So you'd recommend vanity gaps over the patch I have? I didn't actually assume any difference between all the patches, so I had just installed what was convenient.
