### ISSUE TITLE
GTK File Chooser is too big for my screen

### ISSUE THREAD

**Issue by asakura42** [LukeSmithxyz/dwm#213]
Hello. I found that GTK file chooser is bigger than my screen. It's very strange so i need to manually resize this window every time. How can I fix it in dwm?

**Comment by emrakyz** [comment]
[https://github.com/LukeSmithxyz/voidrice/issues/1203](url)

Summary: You can change the size with: "mod+right mouse button" and rearrange with "mod+lmb". It will stay persistent.

**Comment by asakura42** [comment]
@emrakyz 

> [https://github.com/LukeSmithxyz/voidrice/issues/1203](url)
> 
> Summary: You can change the size with: "mod+right mouse button" and rearrange with "mod+lmb". It will stay persistent.

Yes. But it doesn't stay persistent.

**Comment by emrakyz** [comment]
It stays persistent for me. Maybe there are configuration differences. I've recently installed LARBS with Voidrice configs. Then I've made my extra configurations.
