### ISSUE TITLE
libxft-bgra-git orphaned

### ISSUE THREAD

**Issue by BlakePerkins** [LukeSmithxyz/dwm#214]
I recently installed a slightly modified version of Luke's dwm, and every time I sign in, I receive a message saying I need to install libxft-bgra-git from the AUR. However, this package has been orphaned.

Thankfully, I can simply run 'startx' and use my system without any issues (including rendering color emojis), so I assume that libxft takes care of everything on its own now.

What do I need to do so I can get rid this persistent message?

**Comment by shubmehetre** [comment]
I had installed libxft-git which replaced libxft-bgra-git. Getting same issue at login as OP. Now later package is not showing in aur. HELP!!!

**Comment by LukeSmithxyz** [comment]
Just remove the message and check from the `.zprofile`. It's long obsolete now. The normal `libxft` should be sufficient now as it has been updated. No AUR needed.
