### ISSUE TITLE
Darktable captures all shortcuts with Mod4Mask but not with Mod1Mask

### ISSUE THREAD

**Issue by mindtheegab** [LukeSmithxyz/dwm#221]
me and another user of your build are having issues with darktable here : https://github.com/darktable-org/darktable/issues/12737

basically every single shortcut with Super key gets captured by darktable, changing it to Alt fixes the issue

the maintainer there suggested it might be something on your side even though admittedly i only ever encountered that issue with darktable so i opened an issue there first.

using fresh larbs install

**Comment by mindtheegab** [comment]
apologies if this has nothing to do with your build

**Comment by LukeSmithxyz** [comment]
Does this program Darktable use shortcuts with super? If so, that is highly irregular.

Note that this could also be an issue with xcape. In LARBS, xcape allows escape/super to be the same key: escape if pressed, and super if held. It is possible that Darktable is interpreting the key in a non-canonical way.

In either case, I've never heard of a program eating up bind in the way that Darktable is. Probably their issue.

**Comment by mindtheegab** [comment]
they do not use the super key that is the weird thing they were saying a change in how shortcuts are handled was implemented in 3.8(they are now at 4.0.1)  but also saying that kde/gnome handle that fine and dwm by default uses the ALT key so they are not looking into it

thanks i will try to see if xcape affects it

**Comment by mindtheegab** [comment]
sadly removing xcape does not affects the behavior
