### ISSUE TITLE
dwm logout when executing some commands or when opening some website

### ISSUE THREAD

**Issue by Toni500github** [LukeSmithxyz/dwm#227]
when i visit some website, or some github repo, dwm logout 
even when i execute some command like `sensors | awk '/Core 0/ {print "🌡" $3}'`  ( command from sb-cpu on [voidrice](https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar) )

but when i run the original dwm, nothing of these things happens
i run Linuxmint 20.3

**Comment by LukeSmithxyz** [comment]
libxft-rbgra
