### ISSUE TITLE
Resize tiles via mouse similar to bspwm

### ISSUE THREAD

**Issue by redsigma** [LukeSmithxyz/dwm#23]
Is it possible to resize tiles (without going in floating mode) using the mouse. Similar to how it works on bspwm. 

I am trying to move from bspwm to dwm as it has some better modularity and i would like to have some of the basic features from bspwm.

If resizing tiles using the mouse it's not possible, then is it possible to switch tiles position by dragging them over another tile, similar to bspwm.

**Comment by LukeSmithxyz** [comment]
No. Neither of these things would make much sense or be elegant to implement when dwm is stack based and supposed to be layout independent. You'll have to look if someone has made a patch for something like this before.
