### ISSUE TITLE
bug [keybind-profanity]

### ISSUE THREAD

**Issue by Halem998** [LukeSmithxyz/dwm#232]
Upon pressing SUPER+c  I can't manage to get profanity running. When holding the keys I get this epileptic flickering window but it's like blazingly fast. At no point it actually stays there to be worked with.
Might be a more general thing about dwm. I'm a total noob, so I dunno.

**Comment by LukeSmithxyz** [comment]
Do you have Profanity installed and set up?

**Comment by Halem998** [comment]
no i hadnt @_@
