### ISSUE TITLE
Not able to share selected apps or windows in Zoom

### ISSUE THREAD

**Issue by piyushgarg** [LukeSmithxyz/dwm#236]
![image](https://github.com/LukeSmithxyz/dwm/assets/246124/28fa340c-baee-4809-9bc6-ac6fb733e469)

I am not able to see other windows or apps for sharing only the selected app in dwm. It used to work under gnome. It seems there is something which is not implemented or not supported in dwm.

**Comment by swindlesmccoop** [comment]
Is this specific to Luke's build of DWM? Try compiling it from the vanilla suckless code at https://git.suckless.org/dwm/ and see. If it still doesn't work, then this isn't an issue with Luke's build and an issue with DWM itself.
