### ISSUE TITLE
Luke's dwm does not appear after installing (Debian 12 Gnome)

### ISSUE THREAD

**Issue by CaptainMuskrat** [LukeSmithxyz/dwm#237]
I was looking forward to trying Luke's customized version of dwm as an alternative desktop environment to my favorite, GNOME, however after making it I was surprised to discover that dwm does not appear as a selectable desktop environment afterwards. I had installed stock dwm + bemenu before using the synaptic package manager and that worked perfectly fine, but for some reason this just isn't working for me.

Maybe I missed a step, but any help would be appreciated!.

**Comment by ghost** [comment]
dwm does not install a .desktop entry, so your display manager does not find it.
As a solution, move to a TTY and start dwm using xinit instead: `startx /usr/local/bin/dwm`
