### ISSUE TITLE
Brightness keys do not work

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/dwm#25]
I checked and `xbacklight` commands do work. This would be a pretty easy fix, but I don't know the `XK_##` thing for the brightness keys.

**Comment by AlixShahid** [comment]
already solved => [link](https://github.com/LukeSmithxyz/dwm/issues/20)

**Comment by lukerb52** [comment]
Ok. I'll test it out, and if it works I'll do a PR.
