### ISSUE TITLE
dwm crashes when too many window of a program is opened

### ISSUE THREAD

**Issue by divyangchauhan** [LukeSmithxyz/dwm#26]
If I keep Mod + Return pressed dwm crashes. It also happens with other program like brave. I am using default larbs install with arch Linux. If needed any debug data tell me.

**Comment by LukeSmithxyz** [comment]
It looks like dwm crashes when there are too many windows to calculate locations for. I haven't tested this on other builds. I'm going to guess that it's related to my gaps patch, which I can change if that is it, as that's the only thing that I could imagine changing this.

**Comment by kronikpillow** [comment]
hm... it is possible that it has to do with the old vanitygaps patch but not sure ... this doesn't happen on my build of dwm-flexipatch, the vanitygaps patch was heavily modified by its original author after the initial release on suckless.org, it now includes many layouts by default that are full vanitygaps compatible, and this doesn't seem to happen on it

**Comment by LukeSmithxyz** [comment]
I've updated to the new vanitygaps patch, which seems to have solved this issue. I've also added a couple more layouts and organized the layout keys while I'm at it.
