### ISSUE TITLE
Create a dual screen support

### ISSUE THREAD

**Issue by dihak** [LukeSmithxyz/dwm#29]
There is no shortcut to switch monitors

**Comment by LukeSmithxyz** [comment]
Well I don't really use multiple monitors ever. I'm not against adding a binding for it, but I'm not sure what keys I'm comfortable with.

The usual default keys in dwm for moving monitors I use for audio/mpd control.

If anyone has a suggestion, feel free to offer it.

**Comment by drake-newell** [comment]
@LukeSmithxyz you could use left and right arrow keys.

**Comment by LukeSmithxyz** [comment]
Well yeah, I don't really like arrow keys because they're too far away, but I guess it makes sense. I've made that change for now.
