### ISSUE TITLE
Swap Mod+o/O and Mod+i/I

### ISSUE THREAD

**Issue by ainigiri** [LukeSmithxyz/dwm#31]
In larbs.mom says that Mod+i/I increase or decrease the number of master windows, but in config.h Mod+i/I are configured for center the master window, and center and float master window (in larbs.mom says that Mod+o/O should do that thing). Is this a mistake in larbs.mom or in config.h?

**Comment by LukeSmithxyz** [comment]
Oops. Yeah I just messed up putting it in the readme. Will be changed in a second.
