### ISSUE TITLE
Patches name list

### ISSUE THREAD

**Issue by Aazerra** [LukeSmithxyz/dwm#33]
hello luke 😀
can you put your used patches names in readme file or anathor file??

**Comment by drake-newell** [comment]
Or even better upload the diff files to the repo?

**Comment by LukeSmithxyz** [comment]
Well this is a git repository. Use `git log` to look at patches and changes and `git diff` or `diff show` to diff between commits or generate diffs from them.

There's already a list of added features in the readme, but I'm simply not going to be able to constantly maintain a set of patches and diffs that are mutually compatible with my changing build and the vanilla. This is literally what git is for.
