### ISSUE TITLE
patch systray?

### ISSUE THREAD

**Issue by codeitlikemiley** [LukeSmithxyz/dwm#34]
ive manage to patch a systray with your build for 15 minutes it works great ,
but wouldnt it be better if you include this in the patch?

I think most people will go towards this kind of build....
since most apps, thats offers systray will benefit from this

![pic-full-200417-1304-03](https://user-images.githubusercontent.com/28816690/79534051-22839380-80ac-11ea-98cc-bf808a7dccb5.png)

**Comment by codeitlikemiley** [comment]
the only issue im facing is that when theres a mouse event , it only register the first block 
for example if the first block define is volume, 
only the volume will show , and the rest such as wifi, wont show when click...
So i cant merge it,  maybe you can path this? , im not familiar with all the patches u added...
So maybe i have a trouble when adding the patch, that suppose to be not added or deleted

**Comment by LukeSmithxyz** [comment]
Lacking this is a feature.

**Comment by codeitlikemiley** [comment]
I have  a working patch just now, with fix would love to merge it, but somehow My keybindings would be of different to yours that is hard coded in your repo...
can you provide keys which is really intended for dwm and those that are to be bounded or define in sxhkdrc...

**Comment by patosullivan** [comment]
I realize Luke isn't interested in adding this, but just in case anyone else is:

I created a patch that works with luke's dwm build: https://gist.github.com/patosullivan/5d2d3ef5e8c6d9f5361c792c1af1c930

Only adds a few variables to config.h, doesn't touch anything else in there. Most changes are in dwm.c.
