### ISSUE TITLE
Patch Nice to Have

### ISSUE THREAD

**Issue by codeitlikemiley** [LukeSmithxyz/dwm#37]
I have added quite a few patch with your version

such as systray (allows you to show system tray ), pertag (allows you to use different layouts per workspace), warp(focus the mouse on the center of new master useful so you can use keyboard binding related to focus workspace), focusonnetactive (useful if you are opening links on one terminal and the browser is on other workspace, it will open that link and automatically switch to that workspace)

If you think This will be a good to be added to your DWM build , i would like to create a pull request...
but if u think this is enough for now, i can understand...

**Comment by asolopovas** [comment]
I have tried patching it myself with no success thank you for this patch I have added it to my fork

**Comment by asolopovas** [comment]
pobably Luke considers system tray a bloat
