### ISSUE TITLE
dwm does not quit using provided keybindings.

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/dwm#38]
This is a little hard to provide more information for but I'll try! I've recently switched to using your dwm and st. The keybinding inside your config.h for quitting dwm is meta + F2. Now, when I press this, my status bar flickers and if I have my mouse focused on another screen my open terminals will move to the screen that's empty, but it doesn't quit.

I modified to try and change the keybinding to the default meta + shift + q and I still get the same behaviour. I do not get this behaviour on the base dwm build.

Is there a patch that's causing this? Note: I am not using dwmblocks or any status bar. Could this be causing the issue?

**Comment by drake-newell** [comment]
Do you still have the while loop in .xinitrc? That will restart dwm every time it is killed.

**Comment by ghost** [comment]
I do not have any while loops currently in my .xinitrc. I set wallpaper, start picom and run dwm.

**Comment by ghost** [comment]
Ok, so I've just done a simple test of increasing font size and pressing the quit combination. The font does update so dwm *is* restarting, although it's not in my .xinitrc there must be a patch applied that does restart dwm or some other script included. 

Mystery partially solved!

**Comment by drake-newell** [comment]
@wir3 Oh, wait. I'm stupid lol. Mod+F2 id the binding to restart, not quit. Luke recently made a new script bound to mod+backspace called sysact that shuts down, reboots, exits dwm, etc.

**Comment by LukeSmithxyz** [comment]
Super + F2 has never been quit dwm. Sure it runs a function called quit, but with that argument it restarts. These binds are going to change in a coming commits anyway. Use super + backspace as that will remain.

**Comment by dm17** [comment]
> Super + F2 has never been quit dwm. Sure it runs a function called quit, but with that argument it restarts. These binds are going to change in a coming commits anyway. Use super + backspace as that will remain.

Looks like backspace reboots the computer in your config.h... Can't figure out how to quit dwm yet (works with upstream's config.h though)... Changed super key back to alt since I have a very strange keyboard.
Edit: why can't the word "quit" be somewhere? 0_0

**Comment by AlexSyssoyev** [comment]
> > Super + F2 has never been quit dwm. Sure it runs a function called quit, but with that argument it restarts. These binds are going to change in a coming commits anyway. Use super + backspace as that will remain.
> 
> Looks like backspace reboots the computer in your config.h... Can't figure out how to quit dwm yet (works with upstream's config.h though)... Changed super key back to alt since I have a very strange keyboard.
> Edit: why can't the word "quit" be somewhere? 0_0

Super + Backspace opens a menu that allows you to shutdown, reboot, renew dwm, hibernate and logout.

**Comment by dm17** [comment]
> > > Super + F2 has never been quit dwm. Sure it runs a function called quit, but with that argument it restarts. These binds are going to change in a coming commits anyway. Use super + backspace as that will remain.
> > 
> > 
> > Looks like backspace reboots the computer in your config.h... Can't figure out how to quit dwm yet (works with upstream's config.h though)... Changed super key back to alt since I have a very strange keyboard.
> > Edit: why can't the word "quit" be somewhere? 0_0
> 
> Super + Backspace opens a menu that allows you to shutdown, reboot, renew dwm, hibernate and logout.

Doesn't work for me. Can you let me know the line# or dwm function name that does this in config.h? Thanks.

**Comment by AlexSyssoyev** [comment]
[This line](https://github.com/LukeSmithxyz/dwm/blob/484720bbba3e2b175b71dba283c3a84b13e71eea/config.h#L128) which refers to a script in .local/bin

**Comment by dm17** [comment]
> [This line](https://github.com/LukeSmithxyz/dwm/blob/484720bbba3e2b175b71dba283c3a84b13e71eea/config.h#L128) which refers to a script in .local/bin

I don't see anything called sysacl in .local/bin... What am I missing here? 
I did install everything from here (on Void): https://github.com/PlatinumClaridge/voidrice
But then switched back to Luke's dwm & st builds - because PlatinumClaridge didn't document his changes in a PDF like luke :)

**Comment by AlexSyssoyev** [comment]
You can try to pull luke's dotfiles and get it from there. [Sysact](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/sysact) is in the repo's scripts folder.

Edit: I saw in some issue a PlatinumClaridge's message saying that the main problem with applying Voidrice to voidlinux is that void doesn't comes with curl. I guess that if you installed everything you can try to use Larbs again to pull all Luke's voidrice repo. Or if you want to be more selective use a git pull and replace the stuff you want in your own dotfiles.

**Comment by dm17** [comment]
> You can try to pull luke's dotfiles and get it from there. [Sysact](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/sysact) is in the repo's scripts folder.
> 
> Edit: I saw in some issue a PlatinumClaridge's message saying that the main problem with applying Voidrice to voidlinux is that void doesn't comes with curl. I guess that if you installed everything you can try to use Larbs again to pull all Luke's voidrice repo. Or if you want to be more selective use a git pull and replace the stuff you want in your own dotfiles.

Thanks! So I wonder what else I didn't get using PlatinumClaridge's version. Is LARBS idempotent? Can I just re-run Luke's version to make sure I get the rest of the stuff?
I don't understand the curl comment. His script installs loads of apps - so hard to know if PlatinumClaridge or Luke's scripts support Void better... And there's no uninstall script for LARBS, is there?

**Comment by AlexSyssoyev** [comment]
> > You can try to pull luke's dotfiles and get it from there. [Sysact](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/sysact) is in the repo's scripts folder.
> > Edit: I saw in some issue a PlatinumClaridge's message saying that the main problem with applying Voidrice to voidlinux is that void doesn't comes with curl. I guess that if you installed everything you can try to use Larbs again to pull all Luke's voidrice repo. Or if you want to be more selective use a git pull and replace the stuff you want in your own dotfiles.
> 
> Thanks! So I wonder what else I didn't get using PlatinumClaridge's version. Is LARBS idempotent? Can I just re-run Luke's version to make sure I get the rest of the stuff?

Yes you can re-run it but it will overwrite your changes to the dotfiles you have, if you didn't changed any of the files in the voidrice repo you have nothing to worry about. You also can use ``` git pull https://github.com/LukeSmithxyz/voidrice.git``` to get all the dotfiles and merge them manually if you have some configs you want to keep.

> I don't understand the curl comment. His script installs loads of apps - so hard to know if PlatinumClaridge or Luke's scripts support Void better... 

According to PlatinumClaridge The only thing that is missing from voidlinux to be able to execute larbs without problems is curl. If you install it manually you should be able to use larbs as usual and have everything as it should be.

> And there's no uninstall script for LARBS, is there?

No, there isn't. Larbs just installs all the dependencies for voidrice and copies [Luke's dotfiles](https://github.com/LukeSmithxyz/voidrice) into your home directory. If you want to undo Larbs you can just replace all the config files.

**Comment by drake-newell** [comment]
@AlexSyssoyev Void needs a few more programs than just curl, specifically some of the Xorg "-devel" packages to compile and run dwm.

**Comment by AlexSyssoyev** [comment]
@drake-newell Oh I didn't know, I live mainly in Arch. Thanks for the tip.

**Comment by dm17** [comment]
> @AlexSyssoyev Void needs a few more programs than just curl, specifically some of the Xorg "-devel" packages to compile and run dwm.

Thanks, do you maintain a voidrice that mirror's Lukes & supports Void?
For now I'm just going to try to merge .config, .local, .xprofile, .zprofile, and .xinitrc
I did a quick vimdiff between larbs.claridge.xyz & larbs.xyz/larbs.sh - but didn't finish looking for changes that haven't been brought over. Hopefully the main difference is just the dot files now.

**Comment by drake-newell** [comment]
@dm17 My dots are pretty different from Luke's these days, but maybe I would check out PlatinumClaridge's. He also has a Void-specific LARBS script fork. 

EDIT: Looks like you already checked out his dots, nevermind about that.

**Comment by dm17** [comment]
> @dm17 My dots are pretty different from Luke's these days, but maybe I would check out PlatinumClaridge's. He also has a Void-specific LARBS script fork.
> 
> EDIT: Looks like you already checked out his dots, nevermind about that.

@drake-newell Luke's are a good starting place because they're documented. I was mostly looking for a verification on installing them onto Void.
