### ISSUE TITLE
List of patches

### ISSUE THREAD

**Issue by anselal** [LukeSmithxyz/dwm#4]
Hey Luke,

could you perhaps add to the README a list of the patches you use?

That would be really helpful.

**Comment by anselal** [comment]
Or add the diff file in a different branch? That would work too

**Comment by astier** [comment]
Or he could put the patches into a special patches-directory.

**Comment by anselal** [comment]
As I see in his .gitignore file

https://github.com/LukeSmithxyz/dwm/blob/b15dd72e3579ea96e0c14a89e31dcecda1fedf15/.gitignore#L6

he already has a `patches/` folder which is not staged

**Comment by kvannotten** [comment]
Or use something like [quilt](https://savannah.nongnu.org/projects/quilt) that can apply a bunch of patches automatically

**Comment by kronikpillow** [comment]
I wish there was a list of patches he used as well
