### ISSUE TITLE
scratchpad

### ISSUE THREAD

**Issue by GasparVardanyan** [LukeSmithxyz/dwm#40]
Your scratchpad works for just a single terminal window.
You can use this patch to be able to move any window and any amount of windows to scratchpad: https://github.com/GasparVardanyan/dwm-scratchpad

**Comment by LukeSmithxyz** [comment]
I've added another scratchpad patch to my liking in 806bb2a2bfde3d50d7405126729ed2a2544f11ca. I'm not interested in adding new spawned windows to a scratchpad.
