### ISSUE TITLE
exit menu

### ISSUE THREAD

**Issue by GasparVardanyan** [LukeSmithxyz/dwm#41]
You can do something like this: https://imgur.com/a/d5S9PXm

https://github.com/GasparVardanyan/dwm/blob/d1abbb9039514b182eac734b8089fc26ac9279bc/config.h#L156

**Comment by AlexSyssoyev** [comment]
I like the idea, but I think you should do a pull request with the file ready to merge instead of making an issue.

**Comment by GasparVardanyan** [comment]
Yes, I'm sure, but I don't use this fork of dwm and I haven't installed all of the dependencies for this fork so I can't test whether my changes work on this fork or not. But I like Luke's fork and want to help.

**Comment by LukeSmithxyz** [comment]
You mean just icons added? Well, I don't actually ship out LARBS with font-awesome, so I might want to use standard emojis instead to save a package installation.

**Comment by GasparVardanyan** [comment]
Yes, exit-menu with icons would look better.

**Comment by LukeSmithxyz** [comment]
I added some icons. Using emojis though, since they are installed by default. I suppose they'll at least be easier to distinguish now.
