### ISSUE TITLE
dwm-scratchpad upgrade to allow multiple scratchpads just like in i3

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwm#43]
[Multiple scratchpads](https://lists.suckless.org/hackers/2004/17205.html)

with this we could have the calculator spawn in a scratchpad by a single keybinding, and tmux spawn in a separate scratchpad, and a real scratchpad, and what ever you wish, just like in your i3 config ... consider implementing it :) I really miss this feature on dwm :)

**Comment by LukeSmithxyz** [comment]
Added in 806bb2a2bfde3d50d7405126729ed2a2544f11ca.
