### ISSUE TITLE
arrow keys

### ISSUE THREAD

**Issue by adrian-gluu** [LukeSmithxyz/dwm#44]
using your dwm+st+dwmblocks+voidrice in dwm arrow keys Left and Right didnt work, they are set'ed in config.h but still using vim keys Mod+k instead of Mod+Right same with left, how do i switch if config.h is already OK

**Comment by LukeSmithxyz** [comment]
What?

**Comment by AlexSyssoyev** [comment]
Correct me if i'm wrong but i think you want to change the vim keys to the arrow keys, if you changed them in the dwm config.h did you recompiled it?

**Comment by drake-newell** [comment]
Arrow keys switch monitors. What are you asking?

**Comment by adrian-gluu** [comment]
How can I replace Mod+j for Mod+Left , Mod+k for Mod+Right and Mod+Shift+j for Mod+Shift+Left and Mod+Shift+k for Mod+Shift+Right ???

**Comment by drake-newell** [comment]
@adrian-gluu Change it in config.h and "make && sudo make install"
