### ISSUE TITLE
DWM is ignoring the rule for Spotify

### ISSUE THREAD

**Issue by asolopovas** [LukeSmithxyz/dwm#49]
Hi,
If I add the following rule:
`{ "Spotify",                    NULL,       NULL,       1<<2,         1,           0,           0,          0  },`
dwm simply ignores and opens Spotify in active tag, rather than 3 tag. It does work for all other applications but not Spotify. What could be causing such behaviour?

**Comment by kronikpillow** [comment]
your probably setting the wrong class, are you sure its class is Spotify?

**Comment by asolopovas** [comment]
I wish that was the case. 
![2020-05-02_12-11](https://user-images.githubusercontent.com/6893216/80862588-1aac1d80-8c6e-11ea-91b7-3fa9e4628e0c.png)
By the way, I have tried class "spotify", "Spotify Premium", as well as filling title and instance columns but it is being ignored no matter what I do. I even decided to test it with dwm build from distrotube which rendered same result.

**Comment by kenmckenzie** [comment]
[https://wiki.archlinux.org/index.php/Spotify#Not_respecting_window_manager_rules](url)

Its a known issue due to spotify not following ICMMM spec (I had the same issue with i3). There is a hacky workaround on the page but I personally just made peace with it.

**Comment by LukeSmithxyz** [comment]
Okay. Closing. Not our issue then.
