### ISSUE TITLE
dwm xrdb colors not matching

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwm#52]
I recently applied the Nord color scheme on Xresources, and it looks like the color settings in dwm.c don't match what resources applies, I mean its picking the wrong colors, if you compare my terminal/lf with dwm's bar it's a very noticeable difference, I'v noticed this when applying gruvbox color scheme as well, that the colors simply do not match the scheme, well they do, but wrong colors are being applied to it

this is how it looks:
![pic-full-200502-1123-48](https://user-images.githubusercontent.com/48420193/80860383-9c4c7d00-8c67-11ea-9d5c-c57377ad27b2.png)

this is how it should look:
![MuxpNbw](https://user-images.githubusercontent.com/48420193/80860457-fc432380-8c67-11ea-872f-e3bb6235137b.png)

**Comment by kronikpillow** [comment]
dmenu picks the correct colors but dwm doesnt

**Comment by LukeSmithxyz** [comment]
Can you provide the specific lines in your xresources?

**Comment by kronikpillow** [comment]
It's the default Nord color scheme for xresources

```
#define nord0 #2E3440
#define nord1 #3B4252
#define nord2 #434C5E
#define nord3 #4C566A
#define nord4 #D8DEE9
#define nord5 #E5E9F0
#define nord6 #ECEFF4
#define nord7 #8FBCBB
#define nord8 #88C0D0
#define nord9 #81A1C1
#define nord10 #5E81AC
#define nord11 #BF616A
#define nord12 #D08770
#define nord13 #EBCB8B
#define nord14 #A3BE8C
#define nord15 #B48EAD

*.foreground:   nord4
*.background:   nord0
*.cursorColor:  nord4
*fading: 35
*fadeColor: nord3

*.color0: nord1
*.color1: nord11
*.color2: nord14
*.color3: nord13
*.color4: nord9
*.color5: nord15
*.color6: nord8
*.color7: nord5
*.color8: nord3
*.color9: nord11
*.color10: nord14
*.color11: nord13
*.color12: nord9
*.color13: nord15
*.color14: nord7
*.color15: nord6
```

also the colorscheme is very pleasing on the eyes (much nicer then gruvbox), has better syntax highlighting, and kinda goes nice with the default background, consider using it as the default for your dwm/dmenu/st/dunst/ & vim :)

**Comment by drake-newell** [comment]
Yeah, I was wondering why this looked different

**Comment by LukeSmithxyz** [comment]
Well I guess the "issue" is that I have dwm huge the light cyan color for the selected background, while I think the default is blue. I mean this is sort of a subjective thing, but does it actually bother people? Maybe I'll change it.

**Comment by drake-newell** [comment]
@LukeSmithxyz I've wanted to use nord, so I would say it bothers me a little

**Comment by drake-newell** [comment]
@LukeSmithxyz I've wanted to use nord, so I would say it bothers me a little

**Comment by LukeSmithxyz** [comment]
Well if you guys want dmenu, dwm and the lf bar to all be the same color I'll have to change both dmenu and dwm because lf uses color 4 I think.

**Comment by LukeSmithxyz** [comment]
Okay, I've changed the default colors in dwm and dmenu to the more standard blue.
