### ISSUE TITLE
avoid dwm swallow for vimtex autocompile

### ISSUE THREAD

**Issue by AlexSyssoyev** [LukeSmithxyz/dwm#53]
Hello!, i'm trying to use the autocompile function from vimtex to edit a .tex file on vim. But the swallow of dwm keeps putting zathura on top of the vim editor. I tried to set no_swallow for Zathura but no case. Anyone had this problem before? or there is any alternative to vimtex? I will try to find the function that starts zathura in the latexmk source though.

**Comment by LukeSmithxyz** [comment]
Regardless, you can edit whatever is starting zathura to have it run `setsid zathura <filename> &`. I can't tell you the specifics of vimtex.

**Comment by AlexSyssoyev** [comment]
Oh you're right, i don't need vimtex to do this. Just got it, thanks!
