### ISSUE TITLE
Border transparency with st's alpha patch

### ISSUE THREAD

**Issue by alexsmithxyz** [LukeSmithxyz/dwm#54]
I noticed from videos that the alpha patch for st seems to be interfering with the transparency for borders of st windows but not of others. I had the same problem, the following patch seemed to fix it for me:

```diff
diff --git a/drw.c b/drw.c
index 0eb8fe5..292c496 100644
--- a/drw.c
+++ b/drw.c
@@ -189,6 +189,8 @@ drw_clr_create(Drw *drw, Clr *dest, const char *clrname)
 	                       DefaultColormap(drw->dpy, drw->screen),
 	                       clrname, dest))
 		die("error, cannot allocate color '%s'", clrname);
+
+	dest->pixel = (dest->pixel & 0x00ffffffU) | (0xffU << 24);
 }
 
 /* Wrapper to create color schemes. The caller has to call free(3) on the
```

Would submit a PR but I didn't test it very much and I no longer use st's alpha patch.

**Comment by GasparVardanyan** [comment]
why *dest->pixel = (dest->pixel & 0x00ffffffU) | (0xffU << 24);* and not just *dest->pixel |= 0xffu << 24;*?

**Comment by alexsmithxyz** [comment]
> why _dest->pixel = (dest->pixel & 0x00ffffffU) | (0xffU << 24);_ and not just _dest->pixel |= 0xffu << 24;_?

I'm unfamiliar with C. That line is a slightly modified line I got from the dwm alpha patch:
https://dwm.suckless.org/patches/alpha/dwm-alpha-20180613-b69c870.diff

The hunk in particular:
```diff
@@ -180,21 +183,22 @@ drw_fontset_free(Fnt *font)
 }
 
 void
-drw_clr_create(Drw *drw, Clr *dest, const char *clrname)
+drw_clr_create(Drw *drw, Clr *dest, const char *clrname, unsigned int alpha)
 {
 	if (!drw || !dest || !clrname)
 		return;
 
-	if (!XftColorAllocName(drw->dpy, DefaultVisual(drw->dpy, drw->screen),
-	                       DefaultColormap(drw->dpy, drw->screen),
+	if (!XftColorAllocName(drw->dpy, drw->visual, drw->cmap,
 	                       clrname, dest))
 		die("error, cannot allocate color '%s'", clrname);
+
+	dest->pixel = (dest->pixel & 0x00ffffffU) | (alpha << 24);
 }
 
 /* Wrapper to create color schemes. The caller has to call free(3) on the
  * returned color scheme when done using it. */
 Clr *
-drw_scm_create(Drw *drw, const char *clrnames[], size_t clrcount)
+drw_scm_create(Drw *drw, const char *clrnames[], const unsigned int alphas[], size_t clrcount)
 {
 	size_t i;
 	Clr *ret;
```

Perhaps it's only necessary in the original context. As I say, I'm unfamiliar with C.

**Comment by GasparVardanyan** [comment]
From Suckless' mailing lists: https://github.com/szatanjl/dwm/commit/1529909466206016f2101457bbf37c67195714c8

**Comment by alexsmithxyz** [comment]
> From Suckless' mailing lists: [szatanjl/dwm@1529909](https://github.com/szatanjl/dwm/commit/1529909466206016f2101457bbf37c67195714c8)

How I wish I found this in my searches. I'll close seeing as that fix has been implemented in a recent commit.
