### ISSUE TITLE
Outdated parts in the manual

### ISSUE THREAD

**Issue by jcguu95** [LukeSmithxyz/dwm#59]
Disclaimer: I'm not using the latest voidrice of yours.

+ `Mod+Backspace` does not bring up a list of options.
+ The statusbar script is claimed to be located in `~/.local/bin/statusbar/`, which does not exist in my laptop, nor in the current `voidrice` repo.
+ Default file browser `lf` still lacks of a tutorial (invoked by `Mod+F2`).
+ `Mod+`` does not work for me. Perhaps I need to get your collections of emojis?
+ `Mod+D` does not bring up root terminal.

**Comment by drake-newell** [comment]
all of those things are in the current repo

**Comment by AlexSyssoyev** [comment]
Is strange that the [statusbar](https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar) does not exist on your system, but that folder is in the voidrice repo.

And i agree with this Mod+`` not working. I had to change it to the "|" key since i don't use a us keyboard layout and the ` is not comfortable to use. I would move the key to somewhere else.

**Comment by LukeSmithxyz** [comment]
Well, it is actually true that the root terminal doesn't come up, because I removed that bind. I've fixed the documentation. Everything else, yeah, you should actually install the dotfiles before deciding if they're not working...

I've never done a video on lf, so there is none there.

**Comment by jcguu95** [comment]
Oh.. just woke up in the morning and now my post seems to be complaining.. sorry if that's the impression! I just hope this post helps to capture some potential frustrations when more people join the party.

Thanks for pointing out that those are all in the repo!

**Comment by jcguu95** [comment]
### Some fix for those who stop following Luke's ricing setup.

+ `statusbar` can be found [here](https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin/statusbar) and [here](https://github.com/LukeSmithxyz/dwmblocks).

+ For `Mod+Backspace` to work, one needs another little script `sysact`, which can be found [here](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/sysact). Put it in a PATH for it to work.

+ For emojis to work, add the [collection](https://github.com/LukeSmithxyz/voidrice/tree/master/.local/share/larbs) to `~/.local/share/larbs`.
