### ISSUE TITLE
Using deck layout without the mouse

### ISSUE THREAD

**Issue by mokulus** [LukeSmithxyz/dwm#60]
How do you use deck layout without focusing master with the mouse? I like the deck layout because it's very compact, but it's hard to use right now, I need to mouse over to master to keep the window on the right.

**Comment by LukeSmithxyz** [comment]
Ah I see what you mean. You're right, that's needed when you have a lot of non-master windows... I've added https://github.com/LukeSmithxyz/dwm/commit/771df89d2812ed9ce746dc32a666344458abe4fd, which will bind `super-v` to jump to the master.

So select what you want in the deck and return to the master with `super-v` and you will still see the selected window. `super-v` is actually pretty useful just if you need to return to the master generally if you have a lot of windows...
