### ISSUE TITLE
As long as I enable noto color emoji in fontconfig, Chinese cannot be displayed

### ISSUE THREAD

**Issue by Wjinlei** [LukeSmithxyz/dwm#70]
Hello, after I configure the emoji, the Chinese font cannot be displayed. What is the problem?

**Comment by LukeSmithxyz** [comment]
You shouldn't have to manually add colored emojis to the fontconfig,
even for the monospace for them to show up. The same happens on my
machine if I manually put them in font config (and Chinese does not
display), but if I simply do not specify an emoji font, everything,
including the color emoji work.

**Comment by Wjinlei** [comment]
Thank you, I found that it is the reason for my st configuration, it should be that I did not make it right, now I use your st directly. It ’s very easy to use, thank you again
