### ISSUE TITLE
setbg not persisting on reboot 

### ISSUE THREAD

**Issue by sudo-ghost** [LukeSmithxyz/dwm#72]
the wallpaper will set but it will revert back to another wallpaper after reboot. also wasn't sure whether to put this issue in larbs, DWM, or your void rice since setbg is a script in your dot's

**Comment by sudo-ghost** [comment]
i have also tried fbsetbg and xwallpaper and none of them persist on reboot either

**Comment by AlexSyssoyev** [comment]
This has been fixed earlier i think, but you can check this line in ~/.local/bin/setbg

```
bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"
```

This should point to the last saved background, so check if there is a bg file and if it isn't you should change that line to where it has been saved. 
Check also if you have the script updated, since i actually think that luke fixed that already but i can't recall it.

**Comment by sudo-ghost** [comment]
I’ll try that after I get up in the morning and let you know what happens

**Comment by sudo-ghost** [comment]
so there is a background file in .local/share/ names bg and it is my last set background but it still reverts back to the one set before it. i also have the newest version of setbg installed.

**Comment by LukeSmithxyz** [comment]
Okay, how are you setting the wallpaper?

The only persistent way to set the wallpaper is to use the `setbg` script.

**Comment by AlexSyssoyev** [comment]
I've had this problem before, the script on its default uses the ```.config/bg``` instead of ```.local/share/bg```. I don't remember how i fixed it though.

If you remove .config/bg does it work?

**Comment by sudo-ghost** [comment]
> Okay, how are you setting the wallpaper?
> 
> The only persistent way to set the wallpaper is to use the `setbg` script.

so when i set the wallpaper with setbg the wallpaper will change but i when i reboot it changes back to the default larbs wallpaper



> I've had this problem before, the script on its default uses the `.config/bg` instead of `.local/share/bg`. I don't remember how i fixed it though.
> 
> If you remove .config/bg does it work?

so i actually don't have a bg file in .config the bg file is only in .local/share

**Comment by AlexSyssoyev** [comment]
So when you boot you have no wallpaper at all? A grey screen?

If you use `setbg` without any arguments do you get any error?

**Comment by sudo-ghost** [comment]
> So when you boot you have no wallpaper at all? A grey screen?
   
> If you use `setbg` without any arguments do you get any error?

so when i boot it will boot as the default wallpaper you get when larbs is installed (its like some snowy moutains) and when i run setbg it will set my wallpaper thats in .local/share/  but i have to run it every time i boot up my machine

**Comment by AlexSyssoyev** [comment]
do you have `setbg &` in your `~/.xprofile`? I don't know if there is some problem with the script but for a temporary fix you can change `setbg &` to `setbg path/to/image &` and it should work.

**Comment by sudo-ghost** [comment]
> do you have `setbg &` in your `~/.xprofile`? I don't know if there is some problem with the script but for a temporary fix you can change `setbg &` to `setbg path/to/image &` and it should work.

That did work for now. Im not sure if its a problem with the script or a problem on my end though

**Comment by AlexSyssoyev** [comment]
Actually i was just looking at [this](https://github.com/LukeSmithxyz/voidrice/commit/c1e2aa9ffcf1c4ee116b0495b6e8bf6ba67c5188) commit and i realized that the background file that is in .config is called wall. Check if it's there and delete it. Maybe that's the problem.

**Comment by sudo-ghost** [comment]
> Actually i was just looking at [this](https://github.com/LukeSmithxyz/voidrice/commit/c1e2aa9ffcf1c4ee116b0495b6e8bf6ba67c5188) commit and i realized that the background file that is in .config is called wall. Check if it's there and delete it. Maybe that's the problem.

that fixed the problem. i deleted that file then changed `setbg path/to/image` back to `setbg &` now setbg will persist on reboot. Im gonna close the issue now.
