### ISSUE TITLE
Not working "workspace" - on diferent than EN layout

### ISSUE THREAD

**Issue by slavan128** [LukeSmithxyz/dwm#75]
Hello,
I'm on way to solve issue with DWM and not working properly with another keyboard layouts than EN (I mainly use SK - slovak)

I tested on DE (deutsch) - works, no issue
I tested on SK (slovenčina - try it to spell ;) ) - not works, maily because in souce code I cannot ad symbols like +ľščťžýáíé (1234567890 - on english)

In i3 i only changed nubers to caracters and some conflicting bindings, but here it not "just werk"

**Comment by LukeSmithxyz** [comment]
I suppose you'd want to use keycodes to map the keys instead: https://dwm.suckless.org/patches/keycodes/

**Comment by LukeSmithxyz** [comment]
If someone does want to convert mine over to use keycodes, I'm open to it.

Don't know if I have the time myself I don't think. Feel free to open a PR. Obviously it'd be nice to have the corresponding English key commented on the line.
