### ISSUE TITLE
video screen freeze while switch workspace

### ISSUE THREAD

**Issue by Monirzadeh** [LukeSmithxyz/dwm#76]
I play video on work space 1 and switch to any other workspace (for example 5). If i comeback workspace 1, video playback screen get a second lag on video(sound play without any lag).
I test that with VLC and MPV and this happens with both of them

**Comment by dawidpotocki** [comment]
If you are using modesetting driver, switching to xf86-video-intel will fix
this issue. It's funny how everyone recommends modesetting but I always had
more issues with it.

**Comment by ghost** [comment]
I'm assuming you're running arch and have intel hd graphics.
installing `xf86-video-intel` and creating this [https://wiki.archlinux.org/index.php/intel_graphics#Xorg_configuration](url) fixed it for me.

**Comment by svdbase** [comment]
Thank you guys! I had the same problem with modesetting driver on arch linux. Installing `xf86-video-intel` does fix this problem.

**Comment by oakszyjrnrdy** [comment]
Thank you guys! I had the same problem with modesetting driver on arch linux. Installing xf86-video-intel does fix this problem.

**Comment by oakszyjrnrdy** [comment]
However, `xf86-video-intel` has bad performance than modeseting when nvidia prime offloading is used.
