### ISSUE TITLE
Systray patch notes

### ISSUE THREAD

**Issue by kvannotten** [LukeSmithxyz/dwm#8]
For people who also want to add the systray patch, there's an additional change you will have to make.

Change the line: 

`XFillRectangle(dpy, systray->win, drw->gc, 0, 0, w, bh);`

to

`XFillRectangle(dpy, systray->win, XCreateGC(dpy, root, 0 , NULL), 0, 0, w, bh);`

**Comment by kopr12** [comment]
That change didn't actually fixed the problem.

**Comment by kopr12** [comment]
This fixed it for me:

Change three lines

`systray->win = XCreateSimpleWindow(dpy, root, x, m->by, w, bh, 0, 0, scheme[SchemeSel][ColBg].pixel);`
to
`systray->win = XCreateSimpleWindow(dpy, root, x - sp, m->by + vp, w, bh, 0, 0, scheme[SchemeSel][ColBg].pixel);`

`XMoveResizeWindow(dpy, systray->win, x, m->by, w, bh);`
to
`XMoveResizeWindow(dpy, systray->win, x - sp, m->by + vp, w, bh);`

`wc.x = x; wc.y = m->by; wc.width = w; wc.height = bh;`
to
`wc.x = x - sp; wc.y = m->by + vp; wc.width = w; wc.height = bh;`
