### ISSUE TITLE
shiftview opens scratchpads

### ISSUE THREAD

**Issue by dawidpotocki** [LukeSmithxyz/dwm#80]
1. Open `spterm` scratchpad on tag 1
2. Hide `spterm` scratchpad on tag 1
2. Switch to tag 2 using `shiftview`
3. Go back to tag 1 using `shiftview`
4. We can see `spterm` on tag 1 again without opening it

This issue happens with `shiftview` + `scratchpads`.
It doesn't happen for `nextprevtag` + `scratchpads`
or `shiftview` + `scratchpad`/`namedscratchpads`.

**Comment by LukeSmithxyz** [comment]
Yeah, I've noticed this... Haven't looked into it yet.
On 20/06/03 05:12AM, Dawid Potocki wrote:
> 1. Open `spterm` scratchpad on tag 1
> 2. Hide `spterm` scratchpad on tag 1
> 2. Switch to tag 2 using `shiftview`
> 3. Go back to tag 2 using `shiftview`
> 4. We can see `spterm` on tag 1 again without opening it
>
> This issue happens with `shiftview` + `scratchpads`.
> It doesn't happen for `nextprevtag` + `scratchpads`
> or `shiftview` + `scratchpad`/`namedscratchpads`.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/dwm/issues/80

--
https://lukesmith.xyz

**Comment by paniash** [comment]
Is there a fix for this problem yet?

**Comment by dawidpotocki** [comment]
> Is there a fix for this problem yet?

nope, I didn't work much on it recently, because I can kinda live without scratchpad

**Comment by m-althaf** [comment]
Is it because scratchpadtags is not considered in shiftview.c?

**Comment by paniash** [comment]
Please have a look at this thread: https://github.com/bakkeby/patches/issues/12

**Comment by JimKat-1** [comment]
You just need to go to the shiftview() function in shiftview.c and add the line:

nextseltags &= (1 << LENGTH(tags)) - 1; 

before these lines:

if (count < 10) {
        a.i = nextseltags;
        view(&a);
}

**Comment by m-althaf** [comment]
@JimKat-1 Thanks buddy.
