### ISSUE TITLE
Fonts in GTK applications

### ISSUE THREAD

**Issue by churupaha** [LukeSmithxyz/dwm#84]
Hi guys. Who knows are there any way to fix the fonts of GTK applications used for tabs and UI controls... I tried everything but fonts are still ugly in Brave and Chromium.
![pic-selected-200606-2346-02](https://user-images.githubusercontent.com/5605956/83954222-f2f13c00-a84f-11ea-991d-359e537813df.png)

**Comment by dawidpotocki** [comment]
Nothing to do with dwm, change your font in `~/.config/fontconfig/fonts.conf`
from `Linux Biolinum` and `Linux Libertine` to whatever you want.

**Comment by ghost** [comment]
> Nothing to do with dwm, change your font in `~/.config/fontconfig/fonts.conf`
> from `Linux Biolinum` and `Linux Libertine` to whatever you want.

You rock! everything is good now.
![pic-selected-200607-1207-57](https://user-images.githubusercontent.com/5605956/83964743-ae998680-a8b7-11ea-9000-12b5be0578d3.png)

**Comment by dawidpotocki** [comment]
If that works fine for you now @churupaha, you can close this issue.
