### ISSUE TITLE
borders doesn't draw with some windows.

### ISSUE THREAD

**Issue by Bear-LB** [LukeSmithxyz/dwm#85]
E.g in the video: 'Literally stop using i3-gaps & use suckless dwm rn', a brave browser is opened with red border drawn around it. But this current upstream dwm build/larbs doesn't do that ;_;

**Comment by AlexSyssoyev** [comment]
If you take a look in brave's settings. Go to design and there is a setting called "Use system's borders" or something like that. Enable it and you will have borders.

Edit: To clarify, this setting is above the font size selector.

**Comment by Bear-LB** [comment]
thx alot man
