### ISSUE TITLE
Multiple monitors

### ISSUE THREAD

**Issue by pniedzwiedzinski** [LukeSmithxyz/dwm#86]
Hi,

I've decided to give dwm a try, but I discovered couple problems with it and couldn't find the solution. I have a double monitor setup: main screen + side screen for music player / logs etc. Previously I was using i3 and there I could jump to the side screen with mod+10 (or mod+l) and then launch the app. But on dwm I don't know how to do the "jump" - I can only do it with mouse. Did anybody have this problem before and know the solution here?

**Comment by jannec22** [comment]
the default keybindings are:

```
mod+. (mod+period) < -defaults
mod+, (mod+comma) <- defaults
```

but in Luke Smiths's build I believe its:

```
mod+arrow_right
mod_arrow_left
```

if you want to move the window to the other screen just add shift the same like with tags.
mod+shift+arrow_(left/right)

![image](https://user-images.githubusercontent.com/33345694/84113356-b9c0f380-aa2a-11ea-8e58-30947cf865e0.png)
 It is configurable in the config.h file of dwm in the keybindings

**Comment by pniedzwiedzinski** [comment]
Thanks!
