### ISSUE TITLE
 st with tmux session doesn't swallow

### ISSUE THREAD

**Issue by user0210** [LukeSmithxyz/dwm#87]
so, in one of your videos you mentioned that you are using tmux inside your scratchpad st-session.
I tried it with changing the class, instance and title flag in st ( -c, -n, -t) and set it up in dwm, but tmux wont swallow...
Does anyone know what is missing?

**Comment by LukeSmithxyz** [comment]
I don't use tmux. Maybe I had it in an old scratchpad on i3?

Either way, tmux isn't going to work with the patch because tmux doesn't work with anything. It's just a different beast. I mean you could be attached to the same tmux session in 5 different windows. What is supposed to be swallowed?

**Comment by user0210** [comment]
Hello again. I leave this here for those in search.
I wrote this little script "sw" and put it in the $PATH. So now, all I have to do is to prefix the command I want to get swallowed with sw. (...you need the swallow patch of course)

```bash
#!/bin/bash

dir=$(pwd)
sess=$(tmux display-message -p '#S')
tmux detach-client -E "cd $dir && $* && tmux attach -t $sess"
```

I always thought using tmux with st is some kind of "way of light" in regards to be suckless..
Can you tell me the biggest issues you had with it, because I'm buildng my setup around this holy connection and dont want to run into unsolvable problems? 
Until now tmux really prevented me from patching the crap out of my st build...
