### ISSUE TITLE
scratchpad (as in i3wm)

### ISSUE THREAD

**Issue by GasparVardanyan** [LukeSmithxyz/dwm#9]
Hi Luke!
What you think about scratchpad in dwm?
I made it: https://github.com/GasparVardanyan/dwm-scratchpad

**Comment by kronikpillow** [comment]
I would love this in DWM :)

**Comment by LukeSmithxyz** [comment]
This has been added now.

**Comment by kronikpillow** [comment]
@LukeSmithxyz this isn't the same scratchpad as the one on suckless.org, this one allows you to send any window to the scratchpad :) you should check it out

**Comment by bandithijo** [comment]
I'm really wanted scratchpad window which have ability as scratchpad like scratchpad window on i3WM.
It can appear and disappear like a Ninja. Lol.
Your @GasparVardanyan scratchpad provide my need.
So, thank you very much for your hard work.
Good job, Bro!

**Comment by GasparVardanyan** [comment]
You're welcome @bandithijo.

**Comment by GasparVardanyan** [comment]
@bandithijo now starting windows in scratchpad is supported. See the README.md ))
