### ISSUE TITLE
Request: Some left/right mirrored layouts

### ISSUE THREAD

**Issue by q-TheDog** [LukeSmithxyz/dwm#91]
Requesting that some of the layouts you've provided also have mirrored versions as options; more specifically, the ones that benefit from being mirrored left/right for multiple monitors next to each other. The ones I was thinking were tile, deck, spiral, and dwindle. Even if they don't have keybinds set for these new mirrored layouts by default (I'd just set them myself), I was thinking just adding ctrl to the existing keybinds you have for my purpose.

**Comment by LukeSmithxyz** [comment]
Well I won't be doing this myself, but you can check out with most of the alternative layouts I have come from here: https://github.com/bakkeby/dwm-vanitygaps

Those will at least be examples for writing your own. They're all defined in `vanitygaps.c`.
