### ISSUE TITLE
Fonts look ugly

### ISSUE THREAD

**Issue by shahid777-py** [LukeSmithxyz/dwm#94]
Luke from  last week  I'm trying Ur dwm build ..I installed libxft-bgra..fine emojis are fine but the font looks a bit ugly not like in Ur videos.. 

Infact I'm using Ur exact font config  and have installed all the fonts u used in that font config

Can u give me Ur latest ` font config` if u don't mind
Just a request from Ur long time subscriber.

I don't know if the antial aliasing  is disabled or what .. it's enabled by default right..

**Comment by AlexSyssoyev** [comment]
You can try using the font in Xresources. Just use ```xrdb ~/.config/Xresources```. Or if you don't like any font just change it and use any other you want.

**Comment by shahid777-py** [comment]
> You can try using the font in Xresources. Just use `xrdb ~/.config/Xresources`. Or if you don't like any font just change it and use any other you want.

What Ur font config can u send Ur font config completely..

And also just a curious about Luke's current font config

**Comment by shahid777-py** [comment]
It looks like he using some source code fonts

**Comment by AlexSyssoyev** [comment]
> > You can try using the font in Xresources. Just use `xrdb ~/.config/Xresources`. Or if you don't like any font just change it and use any other you want.
> 
> What Ur font config can u send Ur font config completely..
> 
> And also just a curious about Luke's current font config

My fontconfig is just the same as [luke's](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/fontconfig/fonts.conf) But Im using Xresources to change it as i told you earlier.
