### ISSUE TITLE
errors applying patches

### ISSUE THREAD

**Issue by adrian-gluu** [LukeSmithxyz/dwm#96]
<img width="996" alt="Screen Shot 2020-06-28 at 20 53 32" src="https://user-images.githubusercontent.com/11430921/85961594-d6917c80-b981-11ea-879d-c631a70036bb.png">

**Comment by drake-newell** [comment]
Try using the command patch -i --merge <diff file> instead.

**Comment by palladidrago** [comment]
same, how do you apply patches?
